---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop

env:
  IMAGE_NAME: znerolmolecule/molecule-prebuilt
  DOCKER_USERNAME: znerolmoleculeci
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  &image:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: alpine
      IMAGE_FROM: docker.io/library/alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          make FROM="${IMAGE_FROM}" "image/${IMAGE_NAME}:${IMAGE_TAG}"
          make "test/${IMAGE_NAME}:${IMAGE_TAG}"

  <<: *image
    env:
      IMAGE_TAG: centos
      IMAGE_FROM: quay.io/centos/centos:stream9

  <<: *image
    env:
      IMAGE_TAG: debian
      IMAGE_FROM: docker.io/library/debian:latest

  <<: *image
    env:
      IMAGE_TAG: fedora
      IMAGE_FROM: quay.io/fedora/fedora:latest

  <<: *image
    env:
      IMAGE_TAG: opensuse-leap
      IMAGE_FROM: docker.io/opensuse/leap:latest

  <<: *image
    env:
      IMAGE_TAG: ubuntu
      IMAGE_FROM: docker.io/library/ubuntu:latest

  &image-systemd:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: centos
      IMAGE_FROM: quay.io/centos/centos:stream

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          make FROM="${IMAGE_FROM}" BUILD_ARGS="--build-arg=SYSTEMD_PREFIX=${IMAGE_VARIANT_SYSTEMD_PREFIX}" "image-systemd/${IMAGE_NAME}:${IMAGE_TAG}"
          make "test-systemd/${IMAGE_NAME}:${IMAGE_TAG}"

  <<: *image-systemd
    env:
      IMAGE_TAG: fedora
      IMAGE_FROM: quay.io/fedora/fedora:latest

  <<: *image-systemd
    env:
      IMAGE_TAG: opensuse-leap
      IMAGE_FROM: docker.io/opensuse/leap:latest
      IMAGE_VARIANT_SYSTEMD_PREFIX: /usr

  <<: *image-systemd
    env:
      IMAGE_TAG: ubuntu
      IMAGE_FROM: docker.io/library/ubuntu:latest
