---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop

jobs:
  alpine:
    uses: ./.github/workflows/do-build-image.yml
    with:
      image-name: znerolmolecule/molecule-prebuilt
      image-tag: alpine
      image-from: docker.io/library/alpine

  centos:
    uses: ./.github/workflows/do-build-image.yml
    with:
      image-name: znerolmolecule/molecule-prebuilt
      image-tag: centos
      image-from: quay.io/centos/centos:stream

  debian:
    uses: ./.github/workflows/do-build-image.yml
    with:
      image-name: znerolmolecule/molecule-prebuilt
      image-tag: debian
      image-from: docker.io/library/debian:latest

  fedora:
    uses: ./.github/workflows/do-build-image.yml
    with:
      image-name: znerolmolecule/molecule-prebuilt
      image-tag: fedora
      image-from: quay.io/fedora/fedora:latest

  ubuntu:
    uses: ./.github/workflows/do-build-image.yml
    with:
      image-name: znerolmolecule/molecule-prebuilt
      image-tag: ubuntu
      image-from: docker.io/library/ubuntu:latest

  centos-systemd:
    uses: ./.github/workflows/do-build-image-systemd.yml
    with:
      image-name: znerolmolecule/molecule-prebuilt
      image-tag: centos
      image-from: quay.io/centos/centos:stream
      systemd-prefix:

  debian-systemd:
    uses: ./.github/workflows/do-build-image-systemd.yml
    with:
      image-name: znerolmolecule/molecule-prebuilt
      image-tag: debian
      image-from: docker.io/library/debian:latest
      systemd-prefix:

  fedora-systemd:
    uses: ./.github/workflows/do-build-image-systemd.yml
    with:
      image-name: znerolmolecule/molecule-prebuilt
      image-tag: fedora
      image-from: quay.io/fedora/fedora:latest
      systemd-prefix:

  ubuntu-systemd:
    uses: ./.github/workflows/do-build-image-systemd.yml
    with:
      image-name: znerolmolecule/molecule-prebuilt
      image-tag: ubuntu
      image-from: docker.io/library/ubuntu:latest
      systemd-prefix:
