---
name: Build image

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      image-from:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          make FROM="${{ inputs.image-from }}" "image/${{ inputs.image-name }}:${{ inputs.image-tag }}"
          make "test/${{ inputs.image-name }}:${{ inputs.image-tag }}"
