---
name: Build image (systemd)

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      image-from:
        required: true
        type: string
      systemd-prefix:
        required: true
        type: string

env:
  IMAGE_TAG: ${{ inputs.image-tag }}
  IMAGE_FROM: ${{ inputs.image-from }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          make FROM="${{ inputs.image-from }}" BUILD_ARGS="--build-arg=SYSTEMD_PREFIX=${{ inputs.systemd-prefix }}" "image-systemd/${{ inputs.image-name }}:${{ inputs.image-tag }}"
          make "test-systemd/${{ inputs.image-name }}:${{ inputs.image-tag }}"
