---
name: Build image

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      image-from:
        required: true
        type: string
      docker-username:
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install j2cli PyYAML

      - name: Build
        run: |
          make FROM="${{ inputs.image-from }}" "image/${{ inputs.image-name }}:${{ inputs.image-tag }}"
          make "test/${{ inputs.image-name }}:${{ inputs.image-tag }}"

      - name: Push
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | podman login -u "${{ inputs.docker-username }}" --password-stdin docker.io
          podman push ${{ inputs.image-name }}:${{ inputs.image-tag }}
